{
  parserClass="com.tcimba.idea.latex.parser.LatexParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Latex"
  psiImplClassSuffix="Impl"
  psiPackage="com.tcimba.idea.latex.psi"
  psiImplPackage="com.tcimba.idea.latex.psi.impl"

  elementTypeHolderClass="com.tcimba.idea.latex.psi.LatexTypes"
  elementTypeClass="com.tcimba.idea.latex.psi.LatexElementType"
  tokenTypeClass="com.tcimba.idea.latex.psi.LatexTokenType"

  psiImplUtilClass="com.tcimba.idea.latex.psi.impl.LatexPsiImplUtil"
}

latexFile ::= (property|COMMENT|CRLF|BEGIN_ENV|END_ENV|brace|option_symbol|TEXT|COMMAND)*

/*property ::= (KEY SEPARATOR VALUE?)|KEY {
    pin=3
    recoverWhile="recover_property"
    mixin="com.tcimba.idea.latex.psi.impl.LatexNamedElementImpl"
    implements="com.tcimba.idea.latex.psi.LatexNamedElement"
    methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}*/

property ::= (KEY? SEPARATOR VALUE?) | KEY {methods=[getKey getValue]}
brace ::= LBRACE|RBRACE|LBRACKET|RBRACKET|LANGLE|RANGLE|LPAREN|RPAREN
option_symbol ::= OPTION_COMMA|OPTION_EQUAL|OPTION_NAME

//private recover_property ::= !(KEY|SEPARATOR|COMMENT)